#! /bin/bash

declare -a filelist=('t_archive' 't_backup' 't_backupquick' 't_makelist' 't_restore' 't_unarchive')
error=0

clear
echo
echo ────────────────────────────────────────────────────────────────────────────────────────
echo "Installing Terminal Backup And Restore..."
echo ────────────────────────────────────────────────────────────────────────────────────────
echo

for file in "${filelist[@]}"; do
  cp $file /usr/local/bin/$file
  if [ $? == 0 ]; then
    echo "+ [$file] installed successfully!"
    chmod 755 /usr/local/bin/t_archive
    if [ $? != 0 ]; then
      echo "--- [$file] permissions could not be changed! Run [chmod 755 /usr/local/bin/$file] again."
      error=1
    fi
  else
    echo "--- [$file] install failed!!!"
    error=1
  fi
done 

echo
if [ $error == 0 ]; then
  echo "Install successful!"
else
  echo "*** Install failed! See above output for possible reasons why it failed. ***"
fi
echo
