#!/bin/bash

archive=$(pwd)
archive="${archive##*/}.zip"
files=$archive
filelist=".files"

clear
echo
echo ────────────────────────────────────────────────────────────────────────────────────────
echo "Unarchiving files in [$archive]..."
echo ────────────────────────────────────────────────────────────────────────────────────────
echo

if [ ! -f "$archive" ]; then
  echo "Archive [$archive] doesn't exist!"
  echo
  exit
fi

echo ────────────────────────────────────────────────────────────────────────────────────────
unzip $archive
echo ────────────────────────────────────────────────────────────────────────────────────────

echo
